In [3]:
import numpy as np
#csv dados tabelados, delimitador , ; |

In [6]:
valores = np.genfromtxt('arquivo.csv', delimiter=',', skip_header=1)
valores

array([[ 10.,  20.,  30.],
       [ 40.,  50.,  60.],
       [ 70.,  80.,  90.],
       [ 34.,  54.,  23.]])

In [9]:
valores = np.genfromtxt('arquivo2.csv', delimiter=',', skip_header=1)
valores

array([ nan,  nan,  nan,  nan])

In [8]:
valores = np.genfromtxt('arquivo2.csv', delimiter=';', skip_header=1)
valores

array([[ 10.,  20.,  30.],
       [ 40.,  50.,  60.],
       [ 70.,  80.,  90.],
       [ 34.,  54.,  23.]])